import Link from "next/link";
import { Zap } from "lucide-react";

export const metadata = {
  title: "Terms of Service — block67",
  description: "Terms and conditions for using block67 blockchain development platform.",
};

const Section = ({ id, title, children }: { id: string; title: string; children: React.ReactNode }) => (
  <section id={id} className="mb-10">
    <h2 className="text-lg font-bold text-white mb-3">{title}</h2>
    <div className="text-gray-400 text-sm leading-relaxed space-y-3">{children}</div>
  </section>
);

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0f1117]">
      {/* Minimal nav */}
      <nav className="border-b border-white/10 px-6 py-4 flex items-center gap-3">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-indigo-600 flex items-center justify-center">
            <Zap className="w-3.5 h-3.5 text-white" />
          </div>
          <span className="font-bold text-white text-sm">block<span className="text-indigo-400">67</span></span>
        </Link>
        <span className="text-gray-600">/</span>
        <span className="text-gray-400 text-sm">Terms of Service</span>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-white mb-3">Terms of Service</h1>
          <p className="text-gray-500 text-sm">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
          <div className="mt-4 bg-amber-500/10 border border-amber-500/20 rounded-xl px-4 py-3 text-sm text-amber-300">
            <strong>Important:</strong> Blockchain transactions are irreversible. By using block67, you accept full responsibility for all contracts you deploy and all transactions you initiate.
          </div>
        </div>

        <Section id="acceptance" title="1. Acceptance of Terms">
          <p>By accessing or using block67.app ("the Platform", "we", "us", "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform.</p>
          <p>These Terms apply to all visitors, users, and others who access or use the Platform. By continuing to use the Platform after any updates to these Terms, you agree to the updated version.</p>
        </Section>

        <Section id="description" title="2. Description of Service">
          <p>block67 is a no-code platform that allows users to generate, compile, and deploy Ethereum-compatible smart contracts using AI-assisted code generation. The Platform provides:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>AI-generated Solidity smart contract code</li>
            <li>In-browser contract compilation via the Solidity compiler (solc)</li>
            <li>One-click deployment to EVM-compatible blockchains via MetaMask</li>
            <li>Frontend dApp generation and hosting</li>
            <li>Custom domain configuration</li>
          </ul>
        </Section>

        <Section id="blockchain-risks" title="3. Blockchain & Smart Contract Risks">
          <div className="bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-3 text-red-300">
            <strong>Critical Disclaimer — Please read carefully:</strong>
          </div>
          <p><strong className="text-white">Irreversibility:</strong> All blockchain transactions, including smart contract deployments, are permanent and cannot be reversed, modified, or deleted. Once a contract is deployed, it exists on-chain forever. We are not responsible for the consequences of any deployment.</p>
          <p><strong className="text-white">No Financial Advice:</strong> Nothing on block67 constitutes financial, investment, legal, or tax advice. Token launches, NFT projects, and DeFi protocols involve substantial financial risk including total loss of capital.</p>
          <p><strong className="text-white">Gas Fees:</strong> Deploying contracts requires payment of network gas fees in the native currency of the chosen blockchain (ETH, MATIC, BNB, etc.). These fees are paid directly to the blockchain network — not to block67. Gas fees are non-refundable regardless of whether the deployment succeeds or fails.</p>
          <p><strong className="text-white">AI-Generated Code:</strong> Smart contracts generated by our AI are provided as-is. While we use OpenZeppelin v5 standards as a base, AI-generated code may contain bugs, vulnerabilities, or logical errors. You are solely responsible for reviewing, auditing, and testing any contract before deploying to mainnet.</p>
          <p><strong className="text-white">Security Audits:</strong> We strongly recommend obtaining a professional security audit from a reputable auditing firm before deploying any contract intended to hold or transact significant value.</p>
          <p><strong className="text-white">Regulatory Compliance:</strong> Blockchain projects, token issuances, and DeFi protocols may be subject to securities laws, AML/KYC requirements, money transmission regulations, and other legal frameworks in your jurisdiction. You are solely responsible for ensuring your project complies with all applicable laws.</p>
        </Section>

        <Section id="user-responsibilities" title="4. User Responsibilities">
          <p>You agree that you are solely responsible for:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>All contracts you deploy using the Platform</li>
            <li>Any tokens, NFTs, or digital assets you create or distribute</li>
            <li>Ensuring your projects comply with all applicable laws in your jurisdiction</li>
            <li>Protecting your wallet credentials and private keys</li>
            <li>The accuracy of all information you provide to the AI for contract generation</li>
            <li>Understanding the technical and financial implications of blockchain deployment</li>
          </ul>
        </Section>

        <Section id="prohibited" title="5. Prohibited Uses">
          <p>You may not use the Platform to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Create or deploy contracts intended to defraud, scam, or deceive users ("rug pulls", Ponzi schemes, etc.)</li>
            <li>Create pump-and-dump token schemes or market manipulation tools</li>
            <li>Violate any applicable law or regulation</li>
            <li>Infringe on intellectual property rights</li>
            <li>Conduct money laundering or facilitate illegal transactions</li>
            <li>Deploy malicious contracts (drainer contracts, honeypots, etc.)</li>
            <li>Create projects that promote violence, discrimination, or illegal activities</li>
            <li>Attempt to reverse-engineer, decompile, or extract proprietary platform code</li>
          </ul>
          <p>Violation of these prohibitions may result in immediate account termination and may be reported to relevant authorities.</p>
        </Section>

        <Section id="platform-liability" title="6. Platform Liability & Disclaimers">
          <p><strong className="text-white">No Warranty:</strong> THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
          <p><strong className="text-white">Limitation of Liability:</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, block67 SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM, INCLUDING ANY SMART CONTRACTS DEPLOYED THROUGH THE PLATFORM.</p>
          <p><strong className="text-white">No Custody:</strong> block67 does not hold, manage, or have access to your crypto assets or wallet. We do not act as a custodian, exchange, or financial intermediary.</p>
          <p><strong className="text-white">Third-Party Blockchains:</strong> We are not responsible for the functioning, availability, security, or performance of any blockchain network on which you deploy contracts.</p>
          <p><strong className="text-white">AI Accuracy:</strong> AI-generated content is not guaranteed to be accurate, complete, or fit for any particular purpose. Do not rely solely on AI-generated code for production deployments without independent review.</p>
        </Section>

        <Section id="intellectual-property" title="7. Intellectual Property">
          <p><strong className="text-white">Your Contracts:</strong> You own the smart contract code generated for your account. block67 does not claim ownership over contracts you deploy.</p>
          <p><strong className="text-white">Platform IP:</strong> The block67 platform, including its AI models, interface, branding, and infrastructure, is the intellectual property of block67. You may not copy, modify, or distribute the Platform itself.</p>
          <p><strong className="text-white">OpenZeppelin:</strong> Contracts generated using OpenZeppelin are subject to the MIT License. By deploying such contracts, you agree to OpenZeppelin's licensing terms.</p>
        </Section>

        <Section id="accounts" title="8. Accounts & Security">
          <p>You are responsible for maintaining the security of your account credentials. block67 will not be liable for any losses arising from unauthorized access to your account due to your failure to keep credentials secure.</p>
          <p>Wallet-based authentication: Your MetaMask wallet is your identity. Loss of access to your wallet means loss of access to your account. We cannot recover wallet-based accounts.</p>
        </Section>

        <Section id="payments" title="9. Payments & Subscriptions">
          <p>Paid plans are billed as described at the time of purchase. All payments are processed in cryptocurrency (ETH or equivalent) as specified in the plan. Payments are non-refundable unless required by applicable law.</p>
          <p>We reserve the right to modify pricing with 30 days notice to existing subscribers.</p>
        </Section>

        <Section id="termination" title="10. Termination">
          <p>We reserve the right to suspend or terminate your account at any time for violation of these Terms, suspected fraudulent activity, or for any other reason at our sole discretion. Upon termination, your access to the Platform will cease, but contracts already deployed on-chain remain on-chain as blockchain transactions cannot be reversed.</p>
        </Section>

        <Section id="changes" title="11. Changes to Terms">
          <p>We may update these Terms at any time. We will notify users of material changes via email (if provided) or by posting a notice on the Platform. Continued use after changes constitutes acceptance of the new Terms.</p>
        </Section>

        <Section id="governing-law" title="12. Governing Law">
          <p>These Terms are governed by the laws applicable in the jurisdiction where block67 is registered. Any disputes shall be resolved through binding arbitration rather than in court, to the extent permitted by applicable law.</p>
        </Section>

        <Section id="contact" title="13. Contact">
          <p>For questions about these Terms, contact us at: <a href="mailto:sanju.m@catchway.com" className="text-indigo-400 hover:underline">sanju.m@catchway.com</a></p>
        </Section>

        <div className="border-t border-white/10 pt-6 mt-8 text-center">
          <p className="text-xs text-gray-600">These Terms of Service were last updated on {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}.</p>
          <Link href="/dashboard" className="mt-3 inline-block text-xs text-indigo-400 hover:underline">← Back to Dashboard</Link>
        </div>
      </div>
    </div>
  );
}
