// POST /api/projects/[id]/download
// Generates and returns a ZIP of the full smart contract project
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/config";
import { db as prisma } from "@/lib/db/index";
import archiver from "archiver";
import type { TemplateId } from "@/lib/templates/index";

// ── Types ─────────────────────────────────────────────────────────────────────

interface DownloadOptions {
  projectName: string;
  framework: "hardhat" | "foundry" | "truffle";
  network: string;
  solidityVersion: string;
  packageManager: "npm" | "yarn";
  includeTests: boolean;
}

interface GenFile { path: string; content: string }

// ── Solidity contract generators ─────────────────────────────────────────────

function erc20Contracts(cfg: Record<string, string>, ver: string): GenFile[] {
  const name = cfg.tokenName || "MyToken";
  const sym  = cfg.symbol    || "MTK";
  const supply = cfg.totalSupply || "1000000000";
  const desc = cfg.description || "ERC-20 token";
  const mintable = cfg.mintable === "true";
  const burnable = cfg.burnable === "true";

  const burnable_import = burnable ? `\nimport "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";` : "";
  const burnable_inherit = burnable ? ", ERC20Burnable" : "";
  const mint_fn = mintable ? `
    /// @notice Mint new tokens (owner only)
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }` : "";
  const burn_fn = !burnable && mintable ? `
    /// @notice Burn tokens from caller
    function burn(uint256 amount) external {
        _burn(msg.sender, amount);
    }` : "";

  return [{
    path: "contracts/Token.sol",
    content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";${burnable_import}
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC20${burnable_inherit}, Ownable {
    uint256 public constant INITIAL_SUPPLY = ${supply} * (10 ** 18);

    constructor(address initialOwner)
        ERC20("${name}", "${sym}")
        Ownable(initialOwner)
    {
        _mint(initialOwner, INITIAL_SUPPLY);
    }
${mint_fn}${burn_fn}
    /// @notice Recover ERC-20 tokens accidentally sent to this contract
    function recoverERC20(address token, uint256 amount) external onlyOwner {
        IERC20(token).transfer(owner(), amount);
    }
}
`,
  }];
}

function nftContracts(cfg: Record<string, string>, ver: string): GenFile[] {
  const name    = cfg.collectionName || "MyNFT";
  const sym     = cfg.symbol        || "MNFT";
  const supply  = cfg.maxSupply     || "10000";
  const price   = cfg.mintPrice     || "0.05";
  const royalty = cfg.royaltyPct    || "5";
  const desc    = cfg.description   || "NFT Collection";

  return [
    {
      path: "contracts/NFTCollection.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "./RoyaltyManager.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev ERC-721 collection with minting, whitelist and reveal
 * @dev Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC721, Ownable {
    using Counters for Counters.Counter;

    Counters.Counter private _tokenIds;

    uint256 public constant MAX_SUPPLY   = ${supply};
    uint256 public constant MINT_PRICE   = ${price} ether;
    bool    public          publicMint   = false;
    bool    public          revealed     = false;
    string  private         _baseTokenURI;
    string  public          unrevealedURI;

    RoyaltyManager public royaltyManager;

    error MaxSupplyReached();
    error InsufficientPayment();
    error PublicMintNotActive();

    constructor(address initialOwner, string memory _unrevealedURI)
        ERC721("${name}", "${sym}")
        Ownable(initialOwner)
    {
        unrevealedURI = _unrevealedURI;
        royaltyManager = new RoyaltyManager(initialOwner, ${royalty} * 100); // basis points
    }

    // ── Minting ──────────────────────────────────────────────────────────────

    function mint(uint256 quantity) external payable {
        if (!publicMint) revert PublicMintNotActive();
        if (msg.value < MINT_PRICE * quantity) revert InsufficientPayment();
        if (_tokenIds.current() + quantity > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i = 0; i < quantity; i++) {
            _tokenIds.increment();
            _mint(msg.sender, _tokenIds.current());
        }
    }

    function ownerMint(address to, uint256 quantity) external onlyOwner {
        if (_tokenIds.current() + quantity > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i = 0; i < quantity; i++) {
            _tokenIds.increment();
            _mint(to, _tokenIds.current());
        }
    }

    // ── Reveal ───────────────────────────────────────────────────────────────

    function reveal(string memory baseURI) external onlyOwner {
        revealed = true;
        _baseTokenURI = baseURI;
    }

    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);
        if (!revealed) return unrevealedURI;
        return string(abi.encodePacked(_baseTokenURI, Strings.toString(tokenId), ".json"));
    }

    // ── Admin ────────────────────────────────────────────────────────────────

    function setPublicMint(bool active) external onlyOwner { publicMint = active; }

    function withdraw() external onlyOwner {
        (bool ok, ) = payable(owner()).call{value: address(this).balance}("");
        require(ok, "Withdraw failed");
    }

    function totalSupply() external view returns (uint256) { return _tokenIds.current(); }
}
`,
    },
    {
      path: "contracts/RoyaltyManager.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/interfaces/IERC2981.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title RoyaltyManager
 * @notice EIP-2981 royalty standard implementation
 * @dev Generated by block67.app
 */
contract RoyaltyManager is IERC2981, Ownable {
    uint256 public royaltyBps; // e.g. 500 = 5%
    address public royaltyRecipient;

    constructor(address recipient, uint256 bps) Ownable(recipient) {
        royaltyRecipient = recipient;
        royaltyBps       = bps;
    }

    function royaltyInfo(uint256, uint256 salePrice)
        external view override
        returns (address receiver, uint256 royaltyAmount)
    {
        return (royaltyRecipient, (salePrice * royaltyBps) / 10_000);
    }

    function setRoyalty(address recipient, uint256 bps) external onlyOwner {
        require(bps <= 1000, "Max 10%");
        royaltyRecipient = recipient;
        royaltyBps       = bps;
    }

    function supportsInterface(bytes4 interfaceId) public pure override returns (bool) {
        return interfaceId == type(IERC2981).interfaceId;
    }
}
`,
    },
  ];
}

function daoContracts(cfg: Record<string, string>, ver: string): GenFile[] {
  const daoName = cfg.daoName           || "MyDAO";
  const token   = cfg.tokenName         || "GOV";
  const quorum  = cfg.quorumPct         || "4";
  const period  = cfg.votingPeriodDays  || "7";
  const timelock= cfg.timelockDays      || "2";
  const desc    = cfg.description       || "Community governed protocol";

  return [
    {
      path: "contracts/GovernanceToken.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${daoName} Governance Token
 * @notice ERC20Votes token for ${daoName} governance
 * @dev Generated by block67.app
 */
contract ${token.replace(/\s+/g, "")}Token is ERC20Votes, Ownable {
    constructor(address initialOwner)
        ERC20("${daoName} Token", "${token}")
        EIP712("${daoName} Token", "1")
        Ownable(initialOwner)
    {
        _mint(initialOwner, 1_000_000 * 10 ** decimals());
    }

    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }

    // Required overrides
    function _update(address from, address to, uint256 amount)
        internal override(ERC20, ERC20Votes)
    { super._update(from, to, amount); }

    function nonces(address owner)
        public view override(ERC20Permit, Nonces)
        returns (uint256)
    { return super.nonces(owner); }
}
`,
    },
    {
      path: "contracts/Governor.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/governance/Governor.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorSettings.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorCountingSimple.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorVotes.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorVotesQuorumFraction.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorTimelockControl.sol";

/**
 * @title ${daoName} Governor
 * @notice ${desc}
 * @dev Quorum: ${quorum}% · Voting period: ${period} days
 * @dev Generated by block67.app
 */
contract ${daoName.replace(/\s+/g, "")}Governor is
    Governor,
    GovernorSettings,
    GovernorCountingSimple,
    GovernorVotes,
    GovernorVotesQuorumFraction,
    GovernorTimelockControl
{
    constructor(IVotes _token, TimelockController _timelock)
        Governor("${daoName} Governor")
        GovernorSettings(
            1,                                  // voting delay (blocks)
            ${Math.round(parseInt(period) * 7200)}, // voting period (blocks, ~${period} days)
            0                                   // proposal threshold
        )
        GovernorVotes(_token)
        GovernorVotesQuorumFraction(${quorum})  // ${quorum}% quorum
        GovernorTimelockControl(_timelock)
    {}

    // Required overrides
    function votingDelay() public view override(Governor, GovernorSettings) returns (uint256) { return super.votingDelay(); }
    function votingPeriod() public view override(Governor, GovernorSettings) returns (uint256) { return super.votingPeriod(); }
    function quorum(uint256 blockNumber) public view override(Governor, GovernorVotesQuorumFraction) returns (uint256) { return super.quorum(blockNumber); }
    function proposalThreshold() public view override(Governor, GovernorSettings) returns (uint256) { return super.proposalThreshold(); }
    function state(uint256 proposalId) public view override(Governor, GovernorTimelockControl) returns (ProposalState) { return super.state(proposalId); }
    function proposalNeedsQueuing(uint256 proposalId) public view override(Governor, GovernorTimelockControl) returns (bool) { return super.proposalNeedsQueuing(proposalId); }
    function _queueOperations(uint256 proposalId, address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) internal override(Governor, GovernorTimelockControl) returns (uint48) { return super._queueOperations(proposalId, targets, values, calldatas, descriptionHash); }
    function _executeOperations(uint256 proposalId, address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) internal override(Governor, GovernorTimelockControl) { super._executeOperations(proposalId, targets, values, calldatas, descriptionHash); }
    function _cancel(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash) internal override(Governor, GovernorTimelockControl) returns (uint256) { return super._cancel(targets, values, calldatas, descriptionHash); }
    function _executor() internal view override(Governor, GovernorTimelockControl) returns (address) { return super._executor(); }
}
`,
    },
    {
      path: "contracts/TimelockController.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/governance/TimelockController.sol";

/**
 * @title ${daoName} Timelock
 * @notice ${parseInt(timelock) * 86400}s (${timelock} day) delay for approved proposals
 * @dev Generated by block67.app
 */
contract ${daoName.replace(/\s+/g, "")}Timelock is TimelockController {
    constructor(address[] memory proposers, address[] memory executors, address admin)
        TimelockController(
            ${parseInt(timelock) * 86400}, // ${timelock} day delay in seconds
            proposers,
            executors,
            admin
        )
    {}
}
`,
    },
    {
      path: "contracts/Treasury.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

/**
 * @title ${daoName} Treasury
 * @notice Holds ETH and ERC-20 tokens, controlled by governance
 * @dev Generated by block67.app
 */
contract ${daoName.replace(/\s+/g, "")}Treasury is AccessControl {
    bytes32 public constant GOVERNOR_ROLE = keccak256("GOVERNOR_ROLE");

    event ETHReceived(address indexed from, uint256 amount);
    event ETHSent(address indexed to, uint256 amount);
    event ERC20Sent(address indexed token, address indexed to, uint256 amount);

    constructor(address governor, address admin) {
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(GOVERNOR_ROLE, governor);
    }

    receive() external payable { emit ETHReceived(msg.sender, msg.value); }

    function sendETH(address payable to, uint256 amount) external onlyRole(GOVERNOR_ROLE) {
        require(address(this).balance >= amount, "Insufficient ETH");
        (bool ok, ) = to.call{value: amount}("");
        require(ok, "ETH transfer failed");
        emit ETHSent(to, amount);
    }

    function sendERC20(address token, address to, uint256 amount) external onlyRole(GOVERNOR_ROLE) {
        IERC20(token).transfer(to, amount);
        emit ERC20Sent(token, to, amount);
    }

    function ethBalance() external view returns (uint256) { return address(this).balance; }
}
`,
    },
  ];
}

function stakingContracts(cfg: Record<string, string>, ver: string): GenFile[] {
  const token  = cfg.tokenName   || "MyToken";
  const sym    = cfg.symbol      || "MTK";
  const apy    = cfg.apy         || "12";
  const lock   = cfg.lockPeriod  || "30";
  const min    = cfg.minStake    || "100";
  const desc   = cfg.description || "Staking protocol";

  return [
    {
      path: "contracts/StakingPool.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./RewardVault.sol";

/**
 * @title ${token} Staking Pool
 * @notice ${desc}
 * @dev APY: ${apy}% · Lock: ${lock} days · Min stake: ${min} ${sym}
 * @dev Generated by block67.app
 */
contract ${token.replace(/\s+/g, "")}StakingPool is Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    IERC20     public immutable stakingToken;
    RewardVault public immutable rewardVault;

    uint256 public constant MIN_STAKE    = ${min} * 10 ** 18;
    uint256 public constant LOCK_PERIOD  = ${lock} days;
    uint256 public constant BASE_APY_BPS = ${Math.round(parseInt(apy) * 100)}; // ${apy}% in basis points

    struct Position {
        uint256 amount;
        uint256 stakedAt;
        uint256 lastClaim;
    }

    mapping(address => Position) public positions;
    uint256 public totalStaked;

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event RewardsClaimed(address indexed user, uint256 amount);

    error BelowMinimumStake();
    error LockPeriodActive();
    error NothingToUnstake();

    constructor(address token, address initialOwner)
        Ownable(initialOwner)
    {
        stakingToken = IERC20(token);
        rewardVault  = new RewardVault(token, BASE_APY_BPS, initialOwner);
    }

    function stake(uint256 amount) external nonReentrant {
        if (amount < MIN_STAKE) revert BelowMinimumStake();
        _claimPending(msg.sender);
        stakingToken.safeTransferFrom(msg.sender, address(this), amount);
        positions[msg.sender].amount   += amount;
        positions[msg.sender].stakedAt  = block.timestamp;
        positions[msg.sender].lastClaim = block.timestamp;
        totalStaked += amount;
        emit Staked(msg.sender, amount);
    }

    function unstake() external nonReentrant {
        Position storage pos = positions[msg.sender];
        if (pos.amount == 0) revert NothingToUnstake();
        if (block.timestamp < pos.stakedAt + LOCK_PERIOD) revert LockPeriodActive();
        _claimPending(msg.sender);
        uint256 amount = pos.amount;
        pos.amount = 0;
        totalStaked -= amount;
        stakingToken.safeTransfer(msg.sender, amount);
        emit Unstaked(msg.sender, amount);
    }

    function claimRewards() external nonReentrant { _claimPending(msg.sender); }

    function pendingRewards(address user) public view returns (uint256) {
        Position storage pos = positions[user];
        if (pos.amount == 0) return 0;
        uint256 elapsed = block.timestamp - pos.lastClaim;
        return (pos.amount * BASE_APY_BPS * elapsed) / (365 days * 10_000);
    }

    function _claimPending(address user) internal {
        uint256 rewards = pendingRewards(user);
        if (rewards > 0) {
            positions[user].lastClaim = block.timestamp;
            rewardVault.distribute(user, rewards);
            emit RewardsClaimed(user, rewards);
        }
    }
}
`,
    },
    {
      path: "contracts/RewardVault.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title RewardVault
 * @notice Holds and distributes staking rewards
 * @dev Generated by block67.app
 */
contract RewardVault is AccessControl {
    using SafeERC20 for IERC20;

    bytes32 public constant DISTRIBUTOR_ROLE = keccak256("DISTRIBUTOR_ROLE");

    IERC20  public immutable rewardToken;
    uint256 public immutable apyBps;

    event RewardsDistributed(address indexed user, uint256 amount);

    constructor(address token, uint256 _apyBps, address admin) {
        rewardToken = IERC20(token);
        apyBps      = _apyBps;
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
        _grantRole(DISTRIBUTOR_ROLE, msg.sender); // StakingPool
    }

    function distribute(address to, uint256 amount) external onlyRole(DISTRIBUTOR_ROLE) {
        rewardToken.safeTransfer(to, amount);
        emit RewardsDistributed(to, amount);
    }

    function vaultBalance() external view returns (uint256) {
        return rewardToken.balanceOf(address(this));
    }
}
`,
    },
  ];
}

function memeContracts(cfg: Record<string, string>, ver: string): GenFile[] {
  const name = cfg.tokenName    || "DogeMoon";
  const sym  = cfg.symbol       || "DGMN";
  const supply = cfg.totalSupply || "420000000000000";
  const tax  = cfg.taxPct       || "2";
  const desc = cfg.description  || "Community meme token";

  return [
    {
      path: "contracts/MemeToken.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "./TaxManager.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev ${tax}% transfer tax · Anti-bot enabled
 * @dev Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC20, Ownable {
    TaxManager public taxManager;

    bool    public  tradingEnabled = false;
    uint256 public  launchBlock;
    uint256 private constant ANTI_BOT_BLOCKS = 3;

    mapping(address => bool) public isExempt;

    event TradingEnabled(uint256 block);

    error TradingNotEnabled();
    error AntiBotProtection();

    constructor(address initialOwner)
        ERC20("${name}", "${sym}")
        Ownable(initialOwner)
    {
        taxManager    = new TaxManager(initialOwner, ${tax} * 100); // basis points
        isExempt[initialOwner] = true;
        isExempt[address(this)] = true;
        _mint(initialOwner, ${supply} * (10 ** decimals()));
    }

    function enableTrading() external onlyOwner {
        require(!tradingEnabled, "Already enabled");
        tradingEnabled = true;
        launchBlock    = block.number;
        emit TradingEnabled(block.number);
    }

    function _update(address from, address to, uint256 amount) internal override {
        if (from != address(0) && to != address(0)) {
            if (!tradingEnabled && !isExempt[from] && !isExempt[to])
                revert TradingNotEnabled();
            if (block.number <= launchBlock + ANTI_BOT_BLOCKS && !isExempt[from])
                revert AntiBotProtection();

            if (!isExempt[from] && !isExempt[to]) {
                uint256 taxAmount = taxManager.calculateTax(amount);
                if (taxAmount > 0) {
                    super._update(from, address(taxManager), taxAmount);
                    amount -= taxAmount;
                }
            }
        }
        super._update(from, to, amount);
    }

    function setExempt(address account, bool exempt) external onlyOwner {
        isExempt[account] = exempt;
    }
}
`,
    },
    {
      path: "contracts/TaxManager.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title TaxManager
 * @notice Manages buy/sell tax distribution for ${name}
 * @dev Generated by block67.app
 */
contract TaxManager is Ownable {
    uint256 public taxBps; // e.g. 200 = 2%
    address public liquidityWallet;
    address public marketingWallet;
    uint256 public liquidityShare = 50; // 50% to LP
    uint256 public marketingShare = 50; // 50% to marketing

    event TaxDistributed(uint256 toLiquidity, uint256 toMarketing);

    constructor(address initialOwner, uint256 _taxBps) Ownable(initialOwner) {
        taxBps           = _taxBps;
        liquidityWallet  = initialOwner;
        marketingWallet  = initialOwner;
    }

    function calculateTax(uint256 amount) external view returns (uint256) {
        return (amount * taxBps) / 10_000;
    }

    function distributeTax(address token) external onlyOwner {
        // Implementation: split and send to LP + marketing wallets
    }

    function setTax(uint256 bps) external onlyOwner {
        require(bps <= 1000, "Max 10% tax");
        taxBps = bps;
    }

    function setWallets(address lp, address marketing) external onlyOwner {
        liquidityWallet = lp;
        marketingWallet = marketing;
    }
}
`,
    },
    {
      path: "contracts/LiquidityManager.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title LiquidityManager
 * @notice LP lock and auto-liquidity for ${name}
 * @dev Liquidity locked for 2 years · Renounce-ready
 * @dev Generated by block67.app
 */
contract LiquidityManager is Ownable {
    uint256 public unlockTime;
    address public lpToken;
    bool    public renounced = false;

    event LPLocked(address lpToken, uint256 unlockTime);
    event Renounced();

    constructor(address initialOwner) Ownable(initialOwner) {}

    function lockLP(address _lpToken) external onlyOwner {
        lpToken    = _lpToken;
        unlockTime = block.timestamp + 730 days; // 2 years
        emit LPLocked(_lpToken, unlockTime);
    }

    function withdrawLP() external onlyOwner {
        require(block.timestamp >= unlockTime, "LP still locked");
        // Transfer LP tokens back to owner
    }

    function renounceOwnership() public override onlyOwner {
        renounced = true;
        super.renounceOwnership();
        emit Renounced();
    }
}
`,
    },
  ];
}

function generateContracts(id: TemplateId, cfg: Record<string, string>, ver: string): GenFile[] {
  switch (id) {
    case "erc20-token":       return erc20Contracts(cfg, ver);
    case "nft-collection":    return nftContracts(cfg, ver);
    case "dao-governance":    return daoContracts(cfg, ver);
    case "staking-dashboard": return stakingContracts(cfg, ver);
    case "meme-token":        return memeContracts(cfg, ver);
    default:                  return [];
  }
}

// ── Framework config files ────────────────────────────────────────────────────

function hardhatConfig(opts: DownloadOptions): GenFile[] {
  const { projectName, network, solidityVersion, packageManager } = opts;
  const isYarn = packageManager === "yarn";
  const contracts = opts.includeTests ? ["contracts/**/*.sol"] : ["contracts/**/*.sol"];

  const networkConfig: Record<string, string> = {
    ethereum:  "1",
    sepolia:   "11155111",
    polygon:   "137",
    arbitrum:  "42161",
    optimism:  "10",
    localhost: "31337",
  };

  return [
    {
      path: "hardhat.config.js",
      content: `require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config();

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: {
    version: "${solidityVersion}",
    settings: {
      optimizer: { enabled: true, runs: 200 },
    },
  },
  networks: {
    localhost: { url: "http://127.0.0.1:8545" },
    sepolia: {
      url: process.env.RPC_URL || "",
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
      chainId: 11155111,
    },
    ${network !== "localhost" && network !== "sepolia" ? `${network}: {
      url: process.env.RPC_URL || "",
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
      chainId: ${networkConfig[network] ?? "1"},
    },` : ""}
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY || "",
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
  },
};
`,
    },
    {
      path: "package.json",
      content: JSON.stringify({
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "1.0.0",
        description: `Smart contracts for ${projectName} — generated by block67.app`,
        scripts: {
          compile:  "hardhat compile",
          test:     "hardhat test",
          deploy:   `hardhat run scripts/deploy.js --network ${network}`,
          "deploy:local": "hardhat run scripts/deploy.js --network localhost",
          node:     "hardhat node",
          clean:    "hardhat clean",
        },
        devDependencies: {
          "@nomicfoundation/hardhat-toolbox": "^5.0.0",
          "hardhat":                           "^2.22.0",
          "dotenv":                            "^16.4.0",
        },
        dependencies: {
          "@openzeppelin/contracts": "^5.0.0",
        },
      }, null, 2),
    },
  ];
}

function foundryConfig(opts: DownloadOptions): GenFile[] {
  const { projectName, network, solidityVersion } = opts;
  return [
    {
      path: "foundry.toml",
      content: `[profile.default]
src      = "src"
out      = "out"
libs     = ["lib"]
solc     = "${solidityVersion}"
optimizer        = true
optimizer_runs   = 200
via_ir           = false

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia   = "\${SEPOLIA_RPC_URL}"
mainnet   = "\${MAINNET_RPC_URL}"
${network !== "localhost" && network !== "sepolia" && network !== "ethereum" ? `${network}   = "\${${network.toUpperCase()}_RPC_URL}"` : ""}

[etherscan]
mainnet = { key = "\${ETHERSCAN_API_KEY}" }
sepolia = { key = "\${ETHERSCAN_API_KEY}", chain = "sepolia" }
`,
    },
    {
      path: "Makefile",
      content: `# ${projectName} — Foundry Makefile
# Generated by block67.app

include .env

build:
\tforge build

test:
\tforge test -vvv

deploy-local:
\tforge script script/Deploy.s.sol --rpc-url localhost --broadcast

deploy-${network}:
\tforge script script/Deploy.s.sol --rpc-url \${RPC_URL} --broadcast --verify

format:
\tforge fmt

clean:
\tforge clean
`,
    },
  ];
}

function truffleConfig(opts: DownloadOptions): GenFile[] {
  const { projectName, network, solidityVersion } = opts;
  return [
    {
      path: "truffle-config.js",
      content: `require("dotenv").config();
const HDWalletProvider = require("@truffle/hdwallet-provider");

module.exports = {
  networks: {
    development: { host: "127.0.0.1", port: 7545, network_id: "*" },
    ${network !== "localhost" ? `${network}: {
      provider: () => new HDWalletProvider(process.env.PRIVATE_KEY, process.env.RPC_URL),
      network_id: "*",
      gas:      5500000,
      gasPrice: 10000000000,
    },` : ""}
  },
  compilers: {
    solc: {
      version: "${solidityVersion}",
      settings: {
        optimizer: { enabled: true, runs: 200 },
      },
    },
  },
  plugins: ["truffle-plugin-verify"],
  api_keys: { etherscan: process.env.ETHERSCAN_API_KEY },
};
`,
    },
    {
      path: "package.json",
      content: JSON.stringify({
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "1.0.0",
        scripts: {
          compile: "truffle compile",
          test:    "truffle test",
          migrate: `truffle migrate --network ${network}`,
        },
        devDependencies: {
          "@truffle/hdwallet-provider": "^2.1.0",
          "truffle":                    "^5.11.0",
          "dotenv":                     "^16.4.0",
          "truffle-plugin-verify":      "^0.6.0",
        },
        dependencies: { "@openzeppelin/contracts": "^5.0.0" },
      }, null, 2),
    },
  ];
}

// ── Deploy scripts ────────────────────────────────────────────────────────────

function deployScript(
  templateId: TemplateId,
  cfg: Record<string, string>,
  framework: string,
): GenFile {
  const contracts = generateContracts(templateId, cfg, "0.8.20")
    .map((f) => f.path.replace("contracts/", "").replace("src/", "").replace(".sol", ""));

  if (framework === "foundry") {
    return {
      path: "script/Deploy.s.sol",
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
${contracts.map((c) => `import "../src/${c}.sol";`).join("\n")}

contract DeployScript is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        vm.startBroadcast(deployerPrivateKey);

        console.log("Deploying contracts from:", deployer);

${contracts.map((c, i) => `        ${c} ${c.toLowerCase()} = new ${c}(deployer);\n        console.log("${c} deployed to:", address(${c.toLowerCase()}));`).join("\n\n")}

        vm.stopBroadcast();
    }
}
`,
    };
  }

  if (framework === "truffle") {
    return {
      path: "migrations/1_deploy_contracts.js",
      content: `${contracts.map((c) => `const ${c} = artifacts.require("${c}");`).join("\n")}

module.exports = async function (deployer, network, accounts) {
  const [deployer_addr] = accounts;
  console.log("Deploying from:", deployer_addr, "on", network);

${contracts.map((c) => `  await deployer.deploy(${c}, deployer_addr);\n  const ${c.toLowerCase()} = await ${c}.deployed();\n  console.log("${c}:", ${c.toLowerCase()}.address);`).join("\n\n")}
};
`,
    };
  }

  // Hardhat (default)
  return {
    path: "scripts/deploy.js",
    content: `const { ethers } = require("hardhat");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

${contracts.map((c) => `  const ${c}Factory = await ethers.getContractFactory("${c}");
  const ${c.toLowerCase()} = await ${c}Factory.deploy(deployer.address);
  await ${c.toLowerCase()}.waitForDeployment();
  console.log("${c} deployed to:", await ${c.toLowerCase()}.getAddress());`).join("\n\n")}

  console.log("\\n✓ All contracts deployed successfully.");
  console.log("Next: verify on Etherscan with 'npx hardhat verify'");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
`,
  };
}

// ── Test templates ────────────────────────────────────────────────────────────

function testFile(
  templateId: TemplateId,
  cfg: Record<string, string>,
  framework: string,
): GenFile {
  const contracts = generateContracts(templateId, cfg, "0.8.20")
    .map((f) => f.path.replace("contracts/", "").replace("src/", "").replace(".sol", ""));
  const first = contracts[0] ?? "Contract";

  if (framework === "foundry") {
    return {
      path: `test/${first}.t.sol`,
      content: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "../src/${first}.sol";

contract ${first}Test is Test {
    ${first} public instance;
    address  public owner = address(0x1);
    address  public user  = address(0x2);

    function setUp() public {
        vm.startPrank(owner);
        instance = new ${first}(owner);
        vm.stopPrank();
    }

    function test_Deployment() public view {
        assertTrue(address(instance) != address(0));
    }

    function test_OwnerIsSet() public view {
        // Add ownership checks here
    }

    function testFuzz_Example(uint256 amount) public {
        vm.assume(amount > 0 && amount < 1e30);
        // Add fuzz tests here
    }
}
`,
    };
  }

  return {
    path: `test/${first}.test.js`,
    content: `const { expect }    = require("chai");
const { ethers }    = require("hardhat");
const { loadFixture } = require("@nomicfoundation/hardhat-toolbox/network-helpers");

describe("${first}", function () {
  async function deployFixture() {
    const [owner, user1, user2] = await ethers.getSigners();
    const Factory = await ethers.getContractFactory("${first}");
    const instance = await Factory.deploy(owner.address);
    return { instance, owner, user1, user2 };
  }

  describe("Deployment", function () {
    it("Should deploy with correct owner", async function () {
      const { instance, owner } = await loadFixture(deployFixture);
      expect(await instance.owner()).to.equal(owner.address);
    });

    it("Should have correct initial state", async function () {
      const { instance } = await loadFixture(deployFixture);
      expect(instance.target).to.be.properAddress;
    });
  });

  describe("Core Functions", function () {
    it("Should perform core operations", async function () {
      const { instance, owner } = await loadFixture(deployFixture);
      // Add your test cases here
    });
  });
});
`,
  };
}

// ── block67.config.json ───────────────────────────────────────────────────────

function block67Config(
  templateId: TemplateId,
  cfg: Record<string, string>,
  opts: DownloadOptions,
): GenFile {
  return {
    path: "config/block67.config.json",
    content: JSON.stringify({
      generatedBy:     "block67.app",
      generatedAt:     new Date().toISOString(),
      projectName:     opts.projectName,
      templateId,
      framework:       opts.framework,
      network:         opts.network,
      solidityVersion: opts.solidityVersion,
      config:          cfg,
    }, null, 2),
  };
}

// ── .env.example ─────────────────────────────────────────────────────────────

function envExample(opts: DownloadOptions): GenFile {
  const isFoundry = opts.framework === "foundry";
  return {
    path: ".env.example",
    content: `# ${opts.projectName} — Environment Variables
# Copy to .env and fill in your values. NEVER commit .env to git.

# Deployer private key (without 0x prefix)
PRIVATE_KEY=your_private_key_here

# RPC endpoint for ${opts.network}
RPC_URL=https://eth-${opts.network}.g.alchemy.com/v2/your_api_key

# Alchemy API key (optional, for event listeners)
ALCHEMY_API_KEY=your_alchemy_key

# Etherscan API key (for contract verification)
ETHERSCAN_API_KEY=your_etherscan_key
${isFoundry ? `
# Foundry-specific
MAINNET_RPC_URL=https://eth-mainnet.g.alchemy.com/v2/your_api_key
SEPOLIA_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/your_api_key
` : ""}`,
  };
}

// ── README.md ─────────────────────────────────────────────────────────────────

function readme(
  templateId: TemplateId,
  cfg: Record<string, string>,
  opts: DownloadOptions,
): GenFile {
  const { projectName, framework, network, solidityVersion, packageManager } = opts;
  const pm = packageManager;
  const isFoundry = framework === "foundry";
  const contracts = generateContracts(templateId, cfg, solidityVersion)
    .map((f) => f.path.replace("contracts/", "").replace("src/", "").replace(".sol", ""));

  return {
    path: "README.md",
    content: `# ${projectName}

> Generated by [block67.app](https://block67.app) — The AI-powered blockchain app builder

## Overview

| | |
|---|---|
| Template | ${templateId} |
| Framework | ${framework.charAt(0).toUpperCase() + framework.slice(1)} |
| Solidity | ${solidityVersion} |
| Network | ${network} |

## Contracts

${contracts.map((c) => `- \`${c}.sol\``).join("\n")}

## Getting Started

### 1. Install dependencies

\`\`\`bash
${isFoundry ? "# Install Foundry\ncurl -L https://foundry.paradigm.xyz | bash\nfoundryup\n\n# Install OpenZeppelin\nforge install OpenZeppelin/openzeppelin-contracts" : `${pm} install`}
\`\`\`

### 2. Configure environment

\`\`\`bash
cp .env.example .env
# Edit .env with your private key and RPC URL
\`\`\`

### 3. Compile contracts

\`\`\`bash
${isFoundry ? "forge build" : `${pm} run compile`}
\`\`\`

### 4. Run tests

\`\`\`bash
${isFoundry ? "forge test -vvv" : `${pm} test`}
\`\`\`

### 5. Deploy to ${network}

\`\`\`bash
${isFoundry
  ? `forge script script/Deploy.s.sol --rpc-url $RPC_URL --broadcast --verify`
  : framework === "truffle"
    ? `${pm} run migrate -- --network ${network}`
    : `${pm} run deploy`}
\`\`\`

### 6. Verify on Etherscan

\`\`\`bash
${isFoundry
  ? `forge verify-contract <CONTRACT_ADDRESS> <CONTRACT_NAME> --chain ${network}`
  : framework === "truffle"
    ? `${pm} exec truffle run verify ${contracts[0]} --network ${network}`
    : `npx hardhat verify --network ${network} <CONTRACT_ADDRESS> <CONSTRUCTOR_ARGS>`}
\`\`\`

## Security

- Always audit contracts before mainnet deployment
- Never commit \`.env\` to version control
- Test thoroughly on testnet first

---

*Built with [block67.app](https://block67.app)*
`,
  };
}

// ── ZIP builder ───────────────────────────────────────────────────────────────

async function buildZip(files: GenFile[], rootDir: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = archiver("zip", { zlib: { level: 9 } });
    const chunks:  Buffer[] = [];

    archive.on("data",  (chunk: Buffer) => chunks.push(chunk));
    archive.on("end",   () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);

    for (const file of files) {
      archive.append(file.content, { name: `${rootDir}/${file.path}` });
    }

    archive.finalize();
  });
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const project = await prisma.project.findFirst({
    where: { id: params.id, ownerId: session.user.id },
  });
  if (!project) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const opts: DownloadOptions = await req.json();
  const cfg        = project.paramValues as Record<string, string>;
  const templateId = (cfg._templateKey ?? "erc20-token") as TemplateId;
  const rootDir    = opts.projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  const solVer     = opts.solidityVersion ?? "0.8.20";

  // Gather all files
  const contractFiles = generateContracts(templateId, cfg, solVer)
    .map((f) => ({
      ...f,
      // Foundry uses src/ instead of contracts/
      path: opts.framework === "foundry"
        ? f.path.replace("contracts/", "src/")
        : f.path,
    }));

  const configFiles = opts.framework === "hardhat"
    ? hardhatConfig(opts)
    : opts.framework === "foundry"
      ? foundryConfig(opts)
      : truffleConfig(opts);

  const allFiles: GenFile[] = [
    ...contractFiles,
    ...configFiles,
    deployScript(templateId, cfg, opts.framework),
    ...(opts.includeTests ? [testFile(templateId, cfg, opts.framework)] : []),
    block67Config(templateId, cfg, opts),
    envExample(opts),
    readme(templateId, cfg, opts),
    { path: ".gitignore", content: `node_modules/\n.env\nartifacts/\ncache/\nout/\n` },
  ];

  const zipBuffer = await buildZip(allFiles, rootDir);

  return new Response(zipBuffer.buffer as ArrayBuffer, {
    headers: {
      "Content-Type":        "application/zip",
      "Content-Disposition": `attachment; filename="${rootDir}.zip"`,
      "Content-Length":      zipBuffer.length.toString(),
    },
  });
}
