/**
 * Block67 Smart Contract Assembler
 *
 * Strategy for how the AI dynamically assembles contracts from the
 * component library so that compilation ALWAYS succeeds.
 *
 * Flow:
 *   1. User describes intent via AI chat
 *   2. AI identifies required modules from AI_MODULE_MAP
 *   3. Assembler generates a Solidity file that imports + inherits the modules
 *   4. VFS resolves all imports (block67/* + @openzeppelin/*)
 *   5. /api/compile returns ABI + Bytecode — zero import errors
 *   6. Deploy tab deploys using ethers.js
 */

import { LIBRARY_VFS, AI_MODULE_MAP } from "./library/index";
import type { TemplateId }            from "@/lib/templates/index";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface AssemblySpec {
  templateId:  TemplateId;
  modules:     string[];          // keys from AI_MODULE_MAP[templateId]
  config:      Record<string, string>;
  version?:    string;
}

export interface AssembledContract {
  source:    string;
  filename:  string;
  imports:   string[];            // library paths used
  baseContracts: string[];        // Solidity contract names inherited
}

// ── Per-template assemblers ───────────────────────────────────────────────────

function assembleERC20(spec: AssemblySpec): AssembledContract {
  const c       = spec.config;
  const name    = (c.tokenName    || "MyToken").replace(/\s+/g, "");
  const sym     = c.symbol        || "MTK";
  const supply  = c.totalSupply   || "1000000";
  const ver     = spec.version    || "0.8.20";

  const mintable = spec.modules.includes("mintable") || c.mintable === "true";
  const burnable = spec.modules.includes("burnable") || c.burnable === "true";
  const taxable  = spec.modules.includes("taxable");
  const votes    = spec.modules.includes("governance");

  const imports: string[] = [];
  const inherits: string[] = ["ERC20", "Ownable"];

  let importBlock = `import "@openzeppelin/contracts/token/ERC20/ERC20.sol";\nimport "@openzeppelin/contracts/access/Ownable.sol";`;

  if (burnable) {
    importBlock += `\nimport "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";`;
    inherits.push("ERC20Burnable");
    imports.push("block67/tokens/ERC20BurnableToken.sol");
  }
  if (votes) {
    importBlock += `\nimport "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";\nimport "@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol";`;
    inherits.push("ERC20Permit", "ERC20Votes");
    imports.push("block67/tokens/ERC20VotesToken.sol");
  }

  const mintFn = mintable ? `
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }` : "";

  const taxBody = taxable ? `
    uint256 public taxBps = ${Number(c.taxPct || 2) * 100};
    address public treasury;
    mapping(address => bool) public isExcluded;

    function _update(address from, address to, uint256 amount) internal override${votes ? "(ERC20, ERC20Votes)" : ""} {
        if (!isExcluded[from] && !isExcluded[to] && taxBps > 0) {
            uint256 tax = (amount * taxBps) / 10_000;
            super._update(from, treasury, tax);
            super._update(from, to, amount - tax);
        } else {
            super._update(from, to, amount);
        }
    }` : "";

  const votesOverrides = votes && !taxable ? `
    function _update(address from, address to, uint256 amount)
        internal override(ERC20, ERC20Votes)
    { super._update(from, to, amount); }

    function nonces(address owner_)
        public view override(ERC20Permit, Nonces) returns (uint256)
    { return super.nonces(owner_); }` : "";

  const constructorExtra = votes ? `\n        ERC20Permit("${name}")` : "";
  const treasuryInit = taxable ? `\n        treasury = initialOwner;` : "";

  const source = `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

${importBlock}

/// @title ${name}
/// @notice ${c.description || "ERC-20 Token generated by block67.app"}
/// @dev AI-assembled from Block67 Component Library
contract ${name} is ${inherits.join(", ")} {
    uint256 public constant INITIAL_SUPPLY = ${supply} * 10 ** 18;

    constructor(address initialOwner)
        ERC20("${c.tokenName || "MyToken"}", "${sym}")${constructorExtra}
        Ownable(initialOwner)
    {${treasuryInit}
        _mint(initialOwner, INITIAL_SUPPLY);
    }
${mintFn}${taxBody}${votesOverrides}
}
`;

  return {
    source,
    filename:  `${name}.sol`,
    imports,
    baseContracts: inherits,
  };
}

function assembleNFT(spec: AssemblySpec): AssembledContract {
  const c      = spec.config;
  const name   = (c.collectionName || "MyNFT").replace(/\s+/g, "");
  const sym    = c.symbol           || "MNFT";
  const supply = c.maxSupply        || "10000";
  const price  = c.mintPrice        || "0.05";
  const ver    = spec.version       || "0.8.20";

  const withRoyalty    = spec.modules.includes("royalty");
  const withSoulbound  = spec.modules.includes("soulbound");
  const withURIStorage = spec.modules.includes("uristorage");

  let importBlock = `import "@openzeppelin/contracts/token/ERC721/ERC721.sol";\nimport "@openzeppelin/contracts/access/Ownable.sol";\nimport "@openzeppelin/contracts/utils/ReentrancyGuard.sol";`;
  const inherits  = ["ERC721", "Ownable", "ReentrancyGuard"];

  if (withRoyalty) {
    importBlock += `\nimport "@openzeppelin/contracts/token/common/ERC2981.sol";`;
    inherits.push("ERC2981");
  }

  const soulboundOverride = withSoulbound ? `
    function _update(address to, uint256 id, address auth)
        internal override returns (address from)
    {
        from = super._update(to, id, auth);
        require(from == address(0) || to == address(0), "Soulbound: non-transferable");
    }` : "";

  const royaltySupports = withRoyalty ? `
    function supportsInterface(bytes4 id)
        public view override(ERC721, ERC2981) returns (bool)
    { return super.supportsInterface(id); }` : "";

  const source = `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

${importBlock}

/// @title ${name}
/// @notice ${c.description || "NFT Collection generated by block67.app"}
contract ${name} is ${inherits.join(", ")} {
    uint256 public constant MAX_SUPPLY = ${supply};
    uint256 public constant MINT_PRICE = ${price} ether;
    uint256 private _nextId = 1;
    bool    public  saleActive;
    string  private _baseUri;

    error SaleNotActive();
    error MaxSupplyReached();
    error InsufficientPayment();

    constructor(address initialOwner)
        ERC721("${c.collectionName || "MyNFT"}", "${sym}")
        Ownable(initialOwner)
    {${withRoyalty ? `\n        _setDefaultRoyalty(initialOwner, ${Number(c.royaltyPct || 5) * 100});` : ""}}

    function mint(uint256 qty) external payable nonReentrant {
        if (!saleActive)                    revert SaleNotActive();
        if (msg.value < MINT_PRICE * qty)   revert InsufficientPayment();
        if (_nextId + qty - 1 > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i; i < qty; ++i) _safeMint(msg.sender, _nextId++);
    }

    function ownerMint(address to, uint256 qty) external onlyOwner {
        if (_nextId + qty - 1 > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i; i < qty; ++i) _safeMint(to, _nextId++);
    }

    function setSaleActive(bool v) external onlyOwner { saleActive = v; }
    function setBaseURI(string calldata u) external onlyOwner { _baseUri = u; }
    function totalMinted() external view returns (uint256) { return _nextId - 1; }
    function _baseURI() internal view override returns (string memory) { return _baseUri; }

    function withdraw() external onlyOwner {
        (bool ok,) = payable(owner()).call{value: address(this).balance}("");
        require(ok, "Withdraw failed");
    }
${soulboundOverride}${royaltySupports}
}
`;

  return {
    source,
    filename:  `${name}.sol`,
    imports:   withRoyalty ? ["block67/nft/ERC721Royalty.sol"] : ["block67/nft/ERC721Mintable.sol"],
    baseContracts: inherits,
  };
}

function assembleStaking(spec: AssemblySpec): AssembledContract {
  const c    = spec.config;
  const name = (c.tokenName || "Staking").replace(/\s+/g, "");
  const ver  = spec.version || "0.8.20";
  const apy  = Math.round(Number(c.apy || 12) * 100);
  const lock = Number(c.lockDays || 30) * 86400;

  const source = `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";

/// @title ${name}StakingPool
/// @notice Staking pool — ${c.apy || 12}% APY, ${c.lockDays || 30}-day lock
/// @dev Generated by block67.app
contract ${name}StakingPool is Ownable, ReentrancyGuard, Pausable {
    using SafeERC20 for IERC20;

    IERC20 public immutable stakeToken;
    IERC20 public immutable rewardToken;

    uint256 public rewardRate;
    uint256 public rewardPerTokenStored;
    uint256 public lastUpdateTime;
    uint256 public totalStaked;
    uint256 public constant APY_BPS    = ${apy};
    uint256 public constant LOCK_SECS  = ${lock};

    mapping(address => uint256) public staked;
    mapping(address => uint256) public userRewardPerTokenPaid;
    mapping(address => uint256) public rewards;
    mapping(address => uint256) public stakedAt;

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event RewardClaimed(address indexed user, uint256 amount);

    constructor(IERC20 stakeToken_, IERC20 rewardToken_, uint256 rewardRate_, address owner_)
        Ownable(owner_)
    {
        stakeToken  = stakeToken_;
        rewardToken = rewardToken_;
        rewardRate  = rewardRate_;
    }

    modifier updateReward(address user) {
        rewardPerTokenStored = rewardPerToken();
        lastUpdateTime = block.timestamp;
        if (user != address(0)) {
            rewards[user] = earned(user);
            userRewardPerTokenPaid[user] = rewardPerTokenStored;
        }
        _;
    }

    function rewardPerToken() public view returns (uint256) {
        if (totalStaked == 0) return rewardPerTokenStored;
        return rewardPerTokenStored + (rewardRate * (block.timestamp - lastUpdateTime) * 1e18) / totalStaked;
    }

    function earned(address user) public view returns (uint256) {
        return (staked[user] * (rewardPerToken() - userRewardPerTokenPaid[user])) / 1e18 + rewards[user];
    }

    function stake(uint256 amount) external nonReentrant whenNotPaused updateReward(msg.sender) {
        require(amount > 0, "Cannot stake 0");
        stakeToken.safeTransferFrom(msg.sender, address(this), amount);
        staked[msg.sender] += amount;
        stakedAt[msg.sender] = block.timestamp;
        totalStaked += amount;
        emit Staked(msg.sender, amount);
    }

    function unstake(uint256 amount) external nonReentrant updateReward(msg.sender) {
        require(staked[msg.sender] >= amount, "Insufficient");
        require(block.timestamp >= stakedAt[msg.sender] + LOCK_SECS, "Still locked");
        staked[msg.sender] -= amount;
        totalStaked -= amount;
        stakeToken.safeTransfer(msg.sender, amount);
        emit Unstaked(msg.sender, amount);
    }

    function claimReward() external nonReentrant updateReward(msg.sender) {
        uint256 reward = rewards[msg.sender];
        if (reward > 0) {
            rewards[msg.sender] = 0;
            rewardToken.safeTransfer(msg.sender, reward);
            emit RewardClaimed(msg.sender, reward);
        }
    }

    function setRewardRate(uint256 rate) external onlyOwner updateReward(address(0)) { rewardRate = rate; }
    function fundRewards(uint256 amount) external onlyOwner { rewardToken.safeTransferFrom(msg.sender, address(this), amount); }
    function pause() external onlyOwner { _pause(); }
    function unpause() external onlyOwner { _unpause(); }
}
`;

  return {
    source,
    filename:      `${name}StakingPool.sol`,
    imports:       ["block67/defi/StakingPool.sol"],
    baseContracts: ["Ownable", "ReentrancyGuard", "Pausable"],
  };
}

// ── Public API ────────────────────────────────────────────────────────────────

/** Assemble a contract for a given template + module selection. */
export function assemble(spec: AssemblySpec): AssembledContract {
  switch (spec.templateId) {
    case "erc20-token":     return assembleERC20(spec);
    case "nft-collection":  return assembleNFT(spec);
    case "staking-dashboard": return assembleStaking(spec);
    default:                return assembleERC20({ ...spec, templateId: "erc20-token" });
  }
}

/** List all available library paths. */
export function listLibrary(): string[] {
  return Object.keys(LIBRARY_VFS);
}

/** Get library contract source by path. */
export function getLibraryContract(path: string): string | undefined {
  return LIBRARY_VFS[path];
}
