// GET /api/projects/[id]/source?version=0.8.20
// Returns the generated Solidity source for a project (first / main contract)
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/config";
import { db as prisma } from "@/lib/db/index";
import type { TemplateId } from "@/lib/templates/index";

// ── Solidity generators (mirrors download route logic) ─────────────────────

function erc20Source(cfg: Record<string, string>, ver: string): string {
  const name     = cfg.tokenName   || "MyToken";
  const sym      = cfg.symbol      || "MTK";
  const supply   = cfg.totalSupply || "1000000000";
  const desc     = cfg.description || "ERC-20 token";
  const mintable = cfg.mintable === "true";
  const burnable = cfg.burnable === "true";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";${burnable ? '\nimport "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";' : ""}
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC20${burnable ? ", ERC20Burnable" : ""}, Ownable {
    uint256 public constant INITIAL_SUPPLY = ${supply} * (10 ** 18);

    constructor(address initialOwner)
        ERC20("${name}", "${sym}")
        Ownable(initialOwner)
    {
        _mint(initialOwner, INITIAL_SUPPLY);
    }
${mintable ? `
    /// @notice Mint new tokens (owner only)
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }` : ""}
    /// @notice Recover ERC-20 tokens accidentally sent to this contract
    function recoverERC20(address token, uint256 amount) external onlyOwner {
        IERC20(token).transfer(owner(), amount);
    }
}
`;
}

function nftSource(cfg: Record<string, string>, ver: string): string {
  const name    = cfg.collectionName || "MyNFT";
  const sym     = cfg.symbol         || "MNFT";
  const supply  = cfg.maxSupply      || "10000";
  const price   = cfg.mintPrice      || "0.05";
  const desc    = cfg.description    || "NFT Collection";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev ERC-721 NFT collection — Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC721, Ownable {
    uint256 public constant MAX_SUPPLY  = ${supply};
    uint256 public constant MINT_PRICE  = ${price} ether;
    bool    public          publicMint  = false;
    uint256 private         _nextId     = 1;
    string  private         _baseURI_;

    error MaxSupplyReached();
    error InsufficientPayment();
    error PublicMintNotActive();

    constructor(address initialOwner)
        ERC721("${name}", "${sym}")
        Ownable(initialOwner)
    {}

    function mint(uint256 quantity) external payable {
        if (!publicMint) revert PublicMintNotActive();
        if (msg.value < MINT_PRICE * quantity) revert InsufficientPayment();
        if (_nextId + quantity - 1 > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i = 0; i < quantity; i++) {
            _safeMint(msg.sender, _nextId++);
        }
    }

    function ownerMint(address to, uint256 quantity) external onlyOwner {
        if (_nextId + quantity - 1 > MAX_SUPPLY) revert MaxSupplyReached();
        for (uint256 i = 0; i < quantity; i++) {
            _safeMint(to, _nextId++);
        }
    }

    function setBaseURI(string memory uri) external onlyOwner { _baseURI_ = uri; }
    function setPublicMint(bool active)    external onlyOwner { publicMint = active; }
    function totalSupply()                 external view returns (uint256) { return _nextId - 1; }

    function withdraw() external onlyOwner {
        (bool ok,) = payable(owner()).call{value: address(this).balance}("");
        require(ok, "Withdraw failed");
    }

    function _baseURI() internal view override returns (string memory) { return _baseURI_; }
}
`;
}

function daoSource(cfg: Record<string, string>, ver: string): string {
  const daoName = cfg.daoName    || "MyDAO";
  const token   = cfg.tokenName  || "GOV";
  const desc    = cfg.description || "Community governed protocol";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${daoName} Governance Token
 * @notice ${desc}
 * @dev Generated by block67.app
 */
contract ${token.replace(/\s+/g, "")}Token is ERC20Votes, Ownable {
    constructor(address initialOwner)
        ERC20("${daoName} Token", "${token}")
        EIP712("${daoName} Token", "1")
        Ownable(initialOwner)
    {
        _mint(initialOwner, 1_000_000 * 10 ** decimals());
    }

    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }

    function _update(address from, address to, uint256 amount)
        internal override(ERC20, ERC20Votes)
    { super._update(from, to, amount); }

    function nonces(address owner)
        public view override(ERC20Permit, Nonces)
        returns (uint256)
    { return super.nonces(owner); }
}
`;
}

function stakingSource(cfg: Record<string, string>, ver: string): string {
  const name = cfg.tokenName || "StakingToken";
  const apy  = cfg.apy        || "12";
  const lock = cfg.lockDays   || "30";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${name} Staking
 * @notice Stake tokens to earn ${apy}% APY with ${lock}-day lock period
 * @dev Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")}Staking is Ownable {
    IERC20 public immutable stakingToken;
    uint256 public constant APY_BPS       = ${Math.round(Number(apy) * 100)}; // ${apy}%
    uint256 public constant LOCK_PERIOD   = ${Number(lock) * 86400};          // ${lock} days

    struct StakeInfo {
        uint256 amount;
        uint256 stakedAt;
        uint256 lastClaim;
    }

    mapping(address => StakeInfo) public stakes;
    uint256 public totalStaked;

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event RewardClaimed(address indexed user, uint256 reward);

    constructor(address _stakingToken, address initialOwner) Ownable(initialOwner) {
        stakingToken = IERC20(_stakingToken);
    }

    function stake(uint256 amount) external {
        require(amount > 0, "Cannot stake 0");
        _claimReward(msg.sender);
        stakingToken.transferFrom(msg.sender, address(this), amount);
        stakes[msg.sender].amount   += amount;
        stakes[msg.sender].stakedAt  = block.timestamp;
        stakes[msg.sender].lastClaim = block.timestamp;
        totalStaked += amount;
        emit Staked(msg.sender, amount);
    }

    function unstake() external {
        StakeInfo storage s = stakes[msg.sender];
        require(s.amount > 0, "Nothing staked");
        require(block.timestamp >= s.stakedAt + LOCK_PERIOD, "Still locked");
        _claimReward(msg.sender);
        uint256 amount = s.amount;
        s.amount = 0;
        totalStaked -= amount;
        stakingToken.transfer(msg.sender, amount);
        emit Unstaked(msg.sender, amount);
    }

    function claimReward() external { _claimReward(msg.sender); }

    function pendingReward(address user) public view returns (uint256) {
        StakeInfo storage s = stakes[user];
        if (s.amount == 0) return 0;
        uint256 elapsed = block.timestamp - s.lastClaim;
        return (s.amount * APY_BPS * elapsed) / (10_000 * 365 days);
    }

    function _claimReward(address user) internal {
        uint256 reward = pendingReward(user);
        if (reward > 0) {
            stakes[user].lastClaim = block.timestamp;
            stakingToken.transfer(user, reward);
            emit RewardClaimed(user, reward);
        }
    }
}
`;
}

function memeSource(cfg: Record<string, string>, ver: string): string {
  const name   = cfg.tokenName   || "MemeToken";
  const sym    = cfg.symbol      || "MEME";
  const supply = cfg.totalSupply || "1000000000";
  const tax    = cfg.taxPct      || "2";
  const desc   = cfg.description || "Community meme token";

  return `// SPDX-License-Identifier: MIT
pragma solidity ^${ver};

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title ${name}
 * @notice ${desc}
 * @dev ${tax}% transfer tax — Generated by block67.app
 */
contract ${name.replace(/\s+/g, "")} is ERC20, Ownable {
    uint256 public constant TOTAL_SUPPLY = ${supply} * (10 ** 18);
    uint256 public taxBps = ${Number(tax) * 100};   // ${tax}%
    address public treasury;
    bool    public taxEnabled = true;

    mapping(address => bool) public isExcludedFromTax;

    event TaxUpdated(uint256 newBps);

    constructor(address initialOwner)
        ERC20("${name}", "${sym}")
        Ownable(initialOwner)
    {
        treasury = initialOwner;
        isExcludedFromTax[initialOwner] = true;
        _mint(initialOwner, TOTAL_SUPPLY);
    }

    function _update(address from, address to, uint256 amount) internal override {
        if (taxEnabled && !isExcludedFromTax[from] && !isExcludedFromTax[to] && taxBps > 0) {
            uint256 taxAmount = (amount * taxBps) / 10_000;
            super._update(from, treasury, taxAmount);
            super._update(from, to, amount - taxAmount);
        } else {
            super._update(from, to, amount);
        }
    }

    function setTax(uint256 bps) external onlyOwner {
        require(bps <= 1000, "Max 10%");
        taxBps = bps;
        emit TaxUpdated(bps);
    }

    function setTaxEnabled(bool enabled) external onlyOwner { taxEnabled = enabled; }
    function excludeFromTax(address account, bool excluded) external onlyOwner {
        isExcludedFromTax[account] = excluded;
    }
}
`;
}

const TEMPLATE_MAP: Record<string, (cfg: Record<string, string>, ver: string) => string> = {
  "erc20-token":      erc20Source,
  "nft-collection":   nftSource,
  "dao-governance":   daoSource,
  "staking-rewards":  stakingSource,
  "meme-token":       memeSource,
};

// ── Route ──────────────────────────────────────────────────────────────────

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const version = req.nextUrl.searchParams.get("version") ?? "0.8.20";

  const project = await prisma.project.findFirst({
    where: { id: params.id, ownerId: session.user.id },
  });

  if (!project) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const cfg        = (project.paramValues ?? {}) as Record<string, string>;
  const templateId = (cfg._templateKey ?? "erc20-token") as TemplateId;
  const generator  = TEMPLATE_MAP[templateId] ?? erc20Source;
  const source     = generator(cfg, version);

  // Derive filename from contract name
  const contractName =
    cfg.tokenName?.replace(/\s+/g, "") ||
    cfg.collectionName?.replace(/\s+/g, "") ||
    cfg.daoName?.replace(/\s+/g, "") ||
    "Contract";

  return NextResponse.json({
    source,
    filename:   `${contractName}.sol`,
    templateId,
    version,
  });
}
